"""Add relationships for Booking

Revision ID: 3f44bf6f23b7
Revises: 9d1bfaf10f56
Create Date: 2026-02-27 12:43:54.681993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f44bf6f23b7'
down_revision = '9d1bfaf10f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('destination_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('travel_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('travel_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('destination_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
