"""Added travel_date to Booking

Revision ID: 9d1bfaf10f56
Revises: c360a983da0c
Create Date: 2026-02-27 11:05:27.759846

"""
from datetime import date
import sqlalchemy as sa
from alembic import op

# Revision identifiers, used by Alembic.
revision = '9d1bfaf10f56'
down_revision = 'c360a983da0c'
branch_labels = None
depends_on = None

def upgrade():
    # Step 1: Add travel_date as nullable
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('travel_date', sa.Date(), nullable=True))

    # Step 2: Set a default for existing rows
    op.execute("UPDATE bookings SET travel_date = '{}' WHERE travel_date IS NULL".format(date.today()))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('travel_date')

    # ### end Alembic commands ###
